version: "3.12"
services:
  backend:
    build: meal_planner_backend
    volumes:
      - ./meal_planner_backend:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG=True
      - PYTHONDONTWRITEBYTECODE=1
      - PYDEVD_DISABLE_FILE_VALIDATION=1  # Add this
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    command: python -X frozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000
    image: backend:django
    container_name: meal_planner_backend
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    container_name: db
    ports:
      - "9998:5432"

  frontend:
    build: meal-planner-ui
    container_name: meal-planner-ui
    ports:
      - "3002:3000"
    env_file:
      - .env
    links:
      - backend
    restart: always